name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version (major | minor | patch | premajor | preminor | prepatch | prerelease)'
        default: 'patch'
        required: true

jobs:
  version:
    name: Create version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 12
    - name: Configure git
      run: |
        git config user.name "CI"
        git config user.email "imnicastelo@gmail.com"
    - name: Create release
      run: npm run release -- --preset eslint --release-as ${{ github.event.inputs.version }}
    - name: Print details
      run: |
        cat package.json
        cat CHANGELOG.md
        git tag
    - name: Push git version
      run: git push --follow-tags origin main
